### ISSUE TITLE
NowPlayingBar disappears sometimes

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-ios#113]
This happened after I deleted a bunch of podcasts in a row:

![image](https://user-images.githubusercontent.com/2262919/32421697-96939c8c-c260-11e7-89f6-84f19a12e17e.png)

**Comment by mitchdowney** [comment]
Maybe fixed in #157 :O ??? 

The tabBarVC appeared to be nil when returning to a previous VC and attempting to update the nowPlayingBar, so the conditional that corrects the bottom constraint did not run.

**Comment by kreonjr** [comment]
Closing for now. Will reopen if we see it again
