### ISSUE TITLE
Display "Could not play media file" alert over any view controller when audioPlayer.state == error

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-ios#136]
I'm not sure how to implement this in the app currently...when a media file errors, the play button will turn red and turn into a "play error" icon, but there should probably be some kind of alert controller message to explain what went wrong. This error can happen while you are on any view controller.

A catch-all error message could be:

"Could not play media file. Either there was a connectivity error, the file no longer exists, or the file is not optimized for streaming playback."

Ideally we don't group all that info into every alert, and instead display only the actual reason for the error.

**Comment by kreonjr** [comment]
You can do something like this from wherever we want it to appear:
```
let alert = UIAlertController(title: "Error", message:"Could not play media file. Either there was a connectivity error, the file no longer exists, or the file is not optimized for streaming playback.", preferredStyle: UIAlertControllerStyle.alert)

alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default, handler: nil))
self.window?.rootViewController?.present(alert, animated: true, completion: nil)
```
