### ISSUE TITLE
Failing to grab correct pubDate for certain podcast RSS feeds

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-ios#2]
When you add Dan Carlin's Hardcore History podcast as an RSS link, every episode ends up getting today's date as the pubDate.

There appears to be a flaw with the retrieveDateFromDateString method where it cannot recognize the date format used by Dan Carlin's Hardcore History podcast.

The feed uses this non-server-friendly timestamp:

`<pubDate>Tue, 24 Jan 2017 21:05:35 PST</pubDate>`

RSS Feed URL: http://feeds.feedburner.com/dancarlin/history?format=xml

**Comment by kreonjr** [comment]
Fixed by https://github.com/podverse/podverse-ios/pull/5
