### ISSUE TITLE
Display some kind of indicator that podcast feeds are parsing

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-ios#43]

**Comment by kreonjr** [comment]
We can indicate this in the podcast table view header. A custom header view might be needed though

**Comment by mitchdowney** [comment]
Should I use this approach instead of dispatch_group? It looks like the previous podverse app did not use dispatch_group, but rather used a ParsingPodcasts array that was updated or cleared...

https://github.com/podverse/podverse/blob/2221d8dda82eefb488a60709c01782af4a720580/podverse/ParsingPodcastsURLs.swift

https://github.com/podverse/podverse/blob/2221d8dda82eefb488a60709c01782af4a720580/podverse/PVFeedParser.swift
