### ISSUE TITLE
Why does setting this array value keep randomly crashing with exc_bad_access error?

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-ios#79]
@kreonjr any ideas what could be causing random unpredictable crashes when setting episodesArray in this conditional?

https://github.com/podverse/podverse-ios/blob/2e51777c3c6c476a027324d0050c04706c6ed259/Podverse/EpisodesTableViewController.swift#L59-L70

**Comment by kreonjr** [comment]
Which line crashes exactly? Do you know? It looks like the app is trying to access either a nil value or a value that is out of bounds.

**Comment by mitchdowney** [comment]
I've seen it crash like that in the else statement on `episodesArray.append(episode) ` a lot. Usually just downloading a bunch of episodes rapidly triggers it within 5-15 tries.

**Comment by mitchdowney** [comment]
This bug is the biggest source of crashes by a lot right now.

**Comment by mitchdowney** [comment]
I haven't seen this for a long time. I think it was an MOC issue fixed somewhere along the way.
